/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:8c96595f-389d-406d-9e31-a9c5e6755e26",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_vhKj84NA9",
    "aws_user_pools_web_client_id": "6viv8deo5lo0kae6mr39m99ir6",
    "oauth": {},
    "aws_cognito_login_mechanisms": [
        "PREFERRED_USERNAME"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "cs443projectapi",
            "endpoint": "https://ynjuzxxa01.execute-api.us-east-2.amazonaws.com/dev",
            "region": "us-east-2"
        }
    ],
    "aws_user_files_s3_bucket": "cs443projectstorage163016-dev",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
